apiVersion: v1
kind: Secret
metadata:
  name: 3scale-provider-details-prod
stringData:
  insecure: 'true'
  provider-domain: https://3scale-admin.apps.ocp.example.com/
  access-token: WlSzKkhkJcYUHKef
