quarkus:
  application:
    name: 3scale-cms

  banner:
    enabled: false

  log:
    console:
      format: '%s%e%n'
    category:
      'io.quarkus':
        level: ERROR
      'com.fwmotion.threscale.cms.cli':
        level: TRACE
    min-level: TRACE

  jib:
    environment-variables:
      # Default to path /cms when in a container (otherwise defaults to .)
      THREESCALE_CMS_ROOT: /cms

  native:
    additional-build-args:
    - --report-unsupported-elements-at-runtime
    - --initialize-at-run-time=com.redhat.threescale.rest.cms.Configuration
    enable-http-url-handler: true
    enable-https-url-handler: true
