name: Build and Publish

on:
  workflow_dispatch: { }
  release:
    types:
    - created

jobs:
  build:
    name: Build and Push to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout 3scale CMS
      uses: actions/checkout@v3

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        settings-path: ${{ github.workspace }}
        server-id: github

    - name: Make repository_owner lowercase for container image group
      id: repo-owner-string
      uses: ASzc/change-string-case-action@v3
      with:
        string: ${{ github.repository_owner }}

    - name: Make repository name lowercase for container image group
      id: repo-name-string
      uses: ASzc/change-string-case-action@v3
      with:
        string: ${{ github.event.repository.name }}

    - name: Maven Build, Deploy, and Push Container Image
      run: >-
        ./mvnw
        --settings ${{ github.workspace }}/settings.xml
        --batch-mode
        deploy
        -Pnative
        -Dquarkus.container-image.build=true
        -Dquarkus.container-image.push=true
        -Dquarkus.container-image.registry=ghcr.io
        -Dquarkus.container-image.group=${{ steps.repo-owner-string.outputs.lowercase }}
        -Dquarkus.container-image.name=${{ steps.repo-name-string.outputs.lowercase }}
        -Dquarkus.container-image.tag=latest
        -Dquarkus.container-image.username=${{ github.actor }}
        -Dquarkus.container-image.password=${{ github.token }}
        -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Delete Old Parent POMs from Maven Repository
      uses: actions/delete-package-versions@v3
      with:
        package-name: 'com.fwmotion.3scale-cms-tools-parent'
        min-versions-to-keep: 3

    - name: Delete Old REST client JARs from Maven Repository
      uses: actions/delete-package-versions@v3
      with:
        package-name: 'com.fwmotion.3scale-cms-rest-client'
        min-versions-to-keep: 3

    - name: Delete Old CLI JARs from Maven Repository
      uses: actions/delete-package-versions@v3
      with:
        package-name: 'com.fwmotion.3scale-cms-tools-cli'
        min-versions-to-keep: 3

    - name: Delete Old Aggregate POMs from Maven Repository
      uses: actions/delete-package-versions@v3
      with:
        package-name: 'com.fwmotion.3scale-cms-tools-aggregate'
        min-versions-to-keep: 3
